---
- name: Gathering service facts.
  service_facts:
  register: services_state

- name: Allow Puppet service port.
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ puppet_port|dict2items }}'
  when:
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
